### ISSUE TITLE
有使用demo吗？

### ISSUE THREAD

**Issue by yu120** [T-baby/ICEREST#1]
楼主你好，强烈建议提供一个demo。其次这个项目只能用sevlet跑吗？能不能直接main方法跑，而不是web.xml?

**Comment by T-baby** [comment]
等mongodb plugin下个版本发布的时候会同时提供demo。之后也会增加用main方法的启动方式。

**Comment by T-baby** [comment]
已经增加了例子 https://github.com/T-baby/ICEREST-EXAMPLE，文档见https://segmentfault.com/blog/icerest
